### PR TITLE
[17.06] Re-vendor swarmkit

### PR DESCRIPTION
**Pull request by cyli**
This includes the following P0+P1 changes from swarmkit:

- [x] https://github.com/docker/swarmkit/pull/2218
- [x] https://github.com/docker/swarmkit/pull/2215
- [x] https://github.com/docker/swarmkit/pull/2233

cc @aaronlehmann

### CODE REVIEW

**Comment by thaJeztah** [comment]
should we bump moby master as well?

**Comment by andrewhsu** [comment]
LGTM

**Comment by cyli** [comment]
@thaJeztah Yes, I'll submit a PR for that.

**Comment by mlaventure** [comment]
@cyli Does this require a line in the changelog? If so, could you provide one?

**Comment by mlaventure** [comment]
@cyli Does this require a line in the changelog? If so, could you provide one?

**Comment by cyli** [comment]
@mlaventure Do you mean a changelog between rc2 and rc3, or changelog between 17.05 and 17.06?

**Comment by mlaventure** [comment]
@cyli since 17.05 we don't do inter-rc changelogs.

If what was fixed wasn't present in 17.05 then no entry is needed.

**Comment by cyli** [comment]
@mlaventure:  https://github.com/docker/swarmkit/pull/2233 was a fix for something that was in 17.05 I think:  Maybe something like "fixed possible orchestration panic in mixed version clusters"?

cc @aaronlehmann

**Comment by aaronlehmann** [comment]
SGTM

**Pull request merged**
