### PR TITLE
update version

### PR DESCRIPTION
**Pull request by vieux**
@andrewhsu @thaJeztah is this even useful ? should the VERSION be `master` or something on the master branch and never change ?

### CODE REVIEW

**Comment by thaJeztah** [comment]
hm, good question; not sure if it's used anywhere in this repo

**Comment by seemethere** [comment]
It's used for packaging

**Comment by vieux** [comment]
yup but since we never package master, I say pinning the version to something like "master" or "dev" could be enough

**Comment by seemethere** [comment]
@vieux We were thinking of doing nightly builds off of master so maybe naming it something akin to `nightly` would probably be more appropriate?

**Comment by vieux** [comment]
@seemethere I would prefer "master" or "dev" for anyone who builds directly from master and jenkins would put nighly when building the nightlies

**Comment by tiborvass** [comment]
What if we removed this file like we're thinking of doing it in engine: https://github.com/moby/moby/pull/33455#issuecomment-318202598

We could simply set the version with an envvar. I'd say this is dependent on moby/moby#33455.
Or we could merge this PR as-is since 17.07 was cut, and postpone the discussion after moby/moby#33455 is decided.

**Comment by vieux** [comment]
@tiborvass it think it's useful to keep the file here, so when you look at a commit, you know for sure the corresponding release

**Comment by vieux** [comment]
(but I still think we should remove it from moby)

**Comment by vieux** [comment]
ping @andrewhsu @seemethere @thaJeztah @tiborvass

**Comment by tiborvass** [comment]
LGTM

**Comment by andrewhsu** [comment]
LGTMM

**Comment by andrewhsu** [comment]
LGTMN

**Pull request merged**
