### PR TITLE
[17.09] backport "plugin refcounting fixes" and "fix labels for remote volumes"

### PR DESCRIPTION
**Pull request by thaJeztah**
cherry-picks of:

- https://github.com/moby/moby/pull/34896/commits/4d8598ad0506b29c12632c1b8ed92eb58fc2f0e2 (https://github.com/moby/moby/pull/34896)
- https://github.com/moby/moby/pull/35265/commits/3816b514387efd24394f0b8e61d55502aa6ac9ac (https://github.com/moby/moby/pull/35265)

For 17.09

### Fixup some issues with plugin refcounting
In some circumstances we were not properly releasing plugin references,
leading to failures in removing a plugin with no way to recover other
than restarting the daemon.

1. If volume create fails (in the driver)
2. If a driver validation fails (should be rare)
3. If trying to get a plugin that does not match the passed in capability

Ideally the test for 1 and 2 would just be a unit test, however the
plugin interfaces are too complicated as `plugingetter` relies on
github.com/pkg/plugin/Client (a concrete type), which will require
spinning up services from within the unit test... it just wouldn't be a
unit test at this point.
I attempted to refactor this a bit, but since both libnetwork and
swarmkit are reliant on `plugingetter` as well, this would not work.
This really requires a re-write of the lower-level plugin management to
decouple these pieces.

### Create labels when volume exists only remotely

Before this, if a volume exists in a driver but not in the local cache,
the store would just return a bare volume. This means that if a user
supplied options or labels, they will not get stored.

Instead only return early if we have the volume stored locally. Note
this could still have an issue with labels/opts passed in by the user
differing from what is stored, however this isn't really a new problem.

This fixes a problem where if there is a shared storage backend between
two docker nodes, a create on one node will have labels stored and a
create on the other node will not.

### CODE REVIEW

**Comment by seemethere** [comment]
Looks like all of the tests are failing with:

```
can't load package: package github.com/docker/docker/integration/plugin: no buildable Go source files in /go/src/github.com/docker/docker/integration/plugin
```

Any reason why this PR would cause that?

**Comment by thaJeztah** [comment]
Possibly because the full test suite was not yet in Docker 17.09 :disappointed:

**Comment by cpuguy83** [comment]
Yep, that's why. moby/moby#35512 replaces that with a unit test.

**Comment by cpuguy83** [comment]
@andrewhsu I can't push to @thaJeztah's branch since I'm not a maintainer on this repo.
Can someone do `git cherry-pick -s -x -Xsubtree=components/engine 00d801dd85b486eb46eff7bd041c33f04e373699`

Commit is pretty new so you'll probably need to fetch it.

**Comment by thaJeztah** [comment]
Thanks @cpuguy83 - added that commit 👍

**Pull request closed without merging**
