### PR TITLE
[17.12] update vndr of swarmkit to a7680ec

### PR DESCRIPTION
**Pull request by andrewhsu**
brings in this change:
 * https://github.com/docker/swarmkit/pull/2513 [17.12] Fix IP overlap with empty EndpointSpec

comparison of changes on the engine: https://github.com/docker/swarmkit/compare/7598f7a...a7680ecc

comparison of changes on the cli: https://github.com/docker/swarmkit/compare/de950a7...a7680ecc

### CODE REVIEW

**Comment by dperny** [comment]
the changes to protobuf are just a weird import path changing thing. not sure how they got introduced, but they're part of a higher-level repository so vendoring that package isn't a concern, and if this builds fine then it works.

**Comment by thaJeztah** [comment]
Not sure what went wrong in the s390x CI;

```
01:56:34 ----------------------------------------------------------------------
01:56:34 FAIL: docker_cli_swarm_test.go:1539: DockerSwarmSuite.TestSwarmNetworkIPAMOptions
01:56:34 
01:56:34 [d8ccc6685ba4c] waiting for daemon to start
01:56:34 [d8ccc6685ba4c] daemon started
01:56:34 
01:56:34 docker_cli_swarm_test.go:1549:
01:56:34     c.Assert(strings.TrimSpace(out), checker.Contains, "com.docker.network.ipam.serial:true")
01:56:34 ... obtained string = "map[foo:bar]"
01:56:34 ... substring string = "com.docker.network.ipam.serial:true"
01:56:34 
01:56:34 [d8ccc6685ba4c] exiting daemon
```

**Comment by anshulpundir** [comment]
Also include https://github.com/docker/swarmkit/pull/2519 in this ? @andrewhsu

**Comment by sebbrandt87** [comment]
what about the failing ce-tests-s390x

**Pull request closed without merging**
