### PR TITLE
Host and Bridge network support in docker stack deploy

### PR DESCRIPTION
**Pull request by mavenugo**
Cherry-picking from https://github.com/docker/cli/pull/132

### CODE REVIEW

**Comment by andrewhsu** [comment]
Seeing error when running `test-integration-cli`:
```
09:58:58 [DockerSwarmSuite] FAIL: docker_cli_swarm_test.go:2197: DockerSwarmSuite.TestSwarmClusterEventsSecret
09:58:58 [DockerSwarmSuite] 
09:58:58 [DockerSwarmSuite] [ddca3132901bd] waiting for daemon to start
09:58:58 [DockerSwarmSuite] [ddca3132901bd] daemon started
09:58:58 [DockerSwarmSuite] 
09:58:58 [DockerSwarmSuite] docker_cli_swarm_test.go:2219:
09:58:58 [DockerSwarmSuite]     c.Assert(out, checker.Contains, "secret remove "+id)
09:58:58 [DockerSwarmSuite] ... obtained string = ""
09:58:58 [DockerSwarmSuite] ... substring string = "secret remove rvuumd98qd5is0zvz5v1qhvz5"
```

**Comment by mavenugo** [comment]
Its a flaky test : https://github.com/moby/moby/issues/33337 and resolved via https://github.com/moby/moby/pull/33307. Should we cherry-pick https://github.com/moby/moby/pull/33307 ?

**Comment by andrewhsu** [comment]
LGTM

all other integration and cli tests are green

**Comment by marcusmartins** [comment]
@thaJeztah @mavenugo Do we need doc changes? I am looking at https://docs.docker.com/compose/swarm/ and https://docs.docker.com/compose/networking/ for reference on how to setup local or bridge network for a service.

**Comment by thaJeztah** [comment]
@marcusmartins can you check if the changes are already in https://github.com/docker/docker.github.io/tree/vnext-compose (which is the branch for the upcoming release), otherwise open an issue in the docs repository (or perhaps create a PR 😇 )

**Pull request merged**
