### PR TITLE
[18.03] backport updates to tests, and fix empty LogPath with non-blocking logging mode

### PR DESCRIPTION
**Pull request by thaJeztah**
Backports for 18.03 of:

- https://github.com/moby/moby/pull/36292 Migrate volumes tests in integration-cli to api tests
- https://github.com/moby/moby/pull/36293 Migrate several docker rm tests to api tests
- https://github.com/moby/moby/pull/36384 Update docker-py This fix update docker-py so that containers from the tests run could be cleaned up during teardown
- https://github.com/moby/moby/pull/36387 Clean the teardown process of network test
- https://github.com/moby/moby/pull/36393 Move containerIsStopped/containerIsInState to integration/internal/container
- https://github.com/moby/moby/pull/36406 Migrate some config secret tests to api test
- https://github.com/moby/moby/pull/36272 Fix empty LogPath with non-blocking logging mode
- https://github.com/moby/moby/pull/36429 Clean up a temp dir created in container unit test
- https://github.com/moby/moby/pull/36430 Migrate config inspect test to api test
- https://github.com/moby/moby/pull/36444 Migrate events tests to api tests
- https://github.com/moby/moby/pull/36445 Remove docker_cli_secret_inspect_test.go
- https://github.com/moby/moby/pull/36450 Enhancement of replacing ContainerCreate with helper funcs in tests
- https://github.com/moby/moby/pull/36455 Fix "expected" and "actual" being reversed
- https://github.com/moby/moby/pull/36459 Migrate export tests to api tests
- https://github.com/moby/moby/pull/36468 Fixes some integration/container tests to run on remote daemon
- https://github.com/moby/moby/pull/36471 Improvement in integration tests
- https://github.com/moby/moby/pull/36474 Migrate docker rm tests to api tests
- https://github.com/moby/moby/pull/36476 Remove unnecessary container.WithName in kill test
- https://github.com/moby/moby/pull/36490 Address `expected` vs `actual` in integration tests
- https://github.com/moby/moby/pull/36493 Adds a unit test for plugin request timeout
- https://github.com/moby/moby/pull/36502 Remove duplicate TestServiceUpdatePort
- https://github.com/moby/moby/pull/36550 Remove unnecessary diff tests
- https://github.com/moby/moby/pull/36569 TestLinksEtcHostsContentMatch: use container.Exec()
- https://github.com/moby/moby/pull/36584 Add some tests to the volume store

This PR also contains a fix; I think it would be ok to include that

- https://github.com/moby/moby/pull/36272 Fix empty LogPath with non-blocking logging mode

After this is merged, https://github.com/docker/docker-ce/pull/468 should be rebased; after that one is merged, there's more changes to the tests we can backport, including the "big one"; https://github.com/moby/moby/pull/36507 Replace testify/assert with gotestyourself/assert

### CODE REVIEW

**Comment by thaJeztah** [comment]
This PR overlaps with https://github.com/docker/docker-ce/pull/512 and https://github.com/docker/docker-ce/pull/510, so we can probably close those. Opened as a separate PR for now to discuss and see if all tests go green

**Comment by thaJeztah** [comment]
Not entirely sure what the failure is in s390x; could it be that there's no more tests in that suite for s390x? https://jenkins.dockerproject.org/job/docker-ce-pr-s390x/549/execution/node/621/log/

```
01:36:52 + make -f Makefile-docker-ce-pr log-DockerAuthzV2Suite.tgz
01:36:52 Makefile-docker-ce-pr:6: warning: overriding recipe for target 'docker-ce'
01:36:52 Makefile-docker-ce:29: warning: ignoring old recipe for target 'docker-ce'
01:36:52 docker run --rm -v /home/ubuntu/workspace/docker-ce-pr-s390x:/v -w /v busybox chown -R 1000:1000 bundles
01:36:53 find bundles -name '*.log' -o -name '*.prof' -o -name integration.test | xargs tar -czf log-DockerAuthzV2Suite.tgz
01:36:53 tar: Cowardly refusing to create an empty archive
01:36:53 Try 'tar --help' or 'tar --usage' for more information.
01:36:53 Makefile-docker-ce:67: recipe for target 'log-DockerAuthzV2Suite.tgz' failed
01:36:53 make: *** [log-DockerAuthzV2Suite.tgz] Error 123

**Comment by andrewhsu** [comment]
I think the error is with [getting the image to run the tests](https://jenkins.dockerproject.org/job/docker-ce-pr-s390x/549/execution/node/587/log/):
```
docker run --rm --privileged --name jenkins-docker-ce-pr-s390x-549-0-a0b317 \
	-v "/home/ubuntu/workspace/docker-ce-pr-s390x/bundles:/go/src/github.com/docker/docker/bundles" \
	-v "/home/ubuntu/workspace/docker-ce-pr-s390x/docker-ce/components/cli/build:/usr/local/cli" \
	-e DOCKER_CLI_PATH=docker \
	-e DOCKER_GITCOMMIT=a3540962fd234faa30385d5f6ef3a96c61610ccd \
	-e TESTFLAGS='-check.f DockerAuthzV2Suite.*' \
	-e KEEPBUNDLE=1 \
	dockerbuildbot/docker@sha256:a19c21e8f86a9c1345789a72436cde7189a524c52f3ebbc6e3b0b0087845d605 hack/make.sh test-integration-cli
Unable to find image 'dockerbuildbot/docker@sha256:a19c21e8f86a9c1345789a72436cde7189a524c52f3ebbc6e3b0b0087845d605' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/dockerbuildbot/docker/manifests/sha256:a19c21e8f86a9c1345789a72436cde7189a524c52f3ebbc6e3b0b0087845d605: EOF.
```

Kicking build again.

**Comment by thaJeztah** [comment]
I think that flakiness  should be fixed by https://github.com/moby/moby/pull/36511, but I see it needs a rebase

**Pull request merged**
