### PR TITLE
[17.06] cherry-pick Fix prefix-matching for service ps

### PR DESCRIPTION
**Pull request by andrewhsu**
Cherry-pick of:
* docker/cli#72 Fix prefix-matching for service ps

### CODE REVIEW

**Comment by andrewhsu** [comment]
Seeing failure in test result:
```
01:00:52.064 [DockerSwarmSuite] FAIL: docker_cli_swarm_test.go:1690: DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs
01:00:52.064 [DockerSwarmSuite] 
01:00:52.064 [DockerSwarmSuite] [d586526176fbf] waiting for daemon to start
01:00:52.064 [DockerSwarmSuite] [d586526176fbf] daemon started
01:00:52.064 [DockerSwarmSuite] 
01:00:52.064 [DockerSwarmSuite] docker_cli_swarm_test.go:1728:
01:00:52.064 [DockerSwarmSuite]     c.Assert(err, checker.IsNil)
01:00:52.064 [DockerSwarmSuite] ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc420218000), Stderr:[]uint8(nil)} ("exit status 1")
01:00:52.064 [DockerSwarmSuite] 
01:00:52.064 [DockerSwarmSuite] [d586526176fbf] exiting daemon
```

**Comment by dnephin** [comment]
I fixed the test to use the proper exec helpers and I can't reproduce the failure, so I guess it's a flake. I'll push the test changes to this branch just in case it isn't.

**Comment by thaJeztah** [comment]
@dnephin should those fixes be backported to moby/moby?

**Comment by dnephin** [comment]
Yes, PR already open: https://github.com/moby/moby/pull/33684 :)

**Comment by thaJeztah** [comment]
Ugh; CI needs a kick;

```
22:34:47 [init] curl: (22) The requested URL returned error: 400 Bad Request
22:34:47 [init] The command '/bin/sh -c ./contrib/download-frozen-image-v2.sh /docker-frozen-images 	buildpack-
```

**Comment by andrewhsu** [comment]
@dnephin with the test debug commit, failed at the same test:
```
00:57:59.454 FAIL: docker_cli_swarm_test.go:1690: DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs
00:57:59.454 
00:57:59.454 [d62ec432a3a1c] waiting for daemon to start
00:57:59.454 [d62ec432a3a1c] daemon started
00:57:59.454 
00:57:59.454 docker_cli_swarm_test.go:1730:
00:57:59.454     result.Assert(c, icmd.Success)
00:57:59.454 /go/src/github.com/docker/docker/pkg/testutil/cmd/command.go:64:
00:57:59.454     t.Fatalf("at %s:%d - %s", filepath.Base(file), line, err.Error())
00:57:59.454 ... Error: at docker_cli_swarm_test.go:1730 - 
00:57:59.454 Command:  /usr/local/cli/docker --host unix:///tmp/docker-integration/d62ec432a3a1c.sock service ps to
00:57:59.454 ExitCode: 1
00:57:59.454 Error:    exit status 1
00:57:59.454 Stdout:   
00:57:59.454 Stderr:   no such service: to
00:57:59.454 
00:57:59.454 
00:57:59.454 Failures:
00:57:59.454 ExitCode was 1 expected 0
00:57:59.454 Expected no error
00:57:59.454 
00:57:59.454 
00:57:59.454 [d62ec432a3a1c] exiting daemon
```

**Comment by thaJeztah** [comment]
I suspect that we need the integration test updates from https://github.com/moby/moby/pull/32800, because current tests test for the faulty behaviour 😞

**Comment by dnephin** [comment]
Test fixed in https://github.com/dnephin/docker-ce/commit/09b371886c5674a39dba8b13a98f01763fd7704f I think.

**Comment by andrewhsu** [comment]
@thaJeztah punting this to 17.06.1

@dnephin i think we talked about this one earlier about splitting out the test that failed into an api test instead of an integration-cli test. would also desire a cherry-pick of something that is already in master branch of moby/moby.

**Comment by dnephin** [comment]
I tried... https://github.com/moby/moby/pull/33684

First I applied this patch to moby/moby, but @thaJeztah pointed out that it doesn't make sense to merge this fix into master, because it shouldn't be testing with the CLI anymore.  Now it's just an API test, but it's being met with some resistance.

**Comment by andrerom** [comment]
Somewhat related given the resistance/test-failures: Any chance of 17.06.01 being releases soon? kind of solves a few blockers, so if this is not, maybe it can be moved to an 17.06.02 milestone?

**Comment by andrewhsu** [comment]
Closing this PR because the docker-ce 17.06 code-line is EoL.

**Pull request closed without merging**
