### PR TITLE
[17.06] Re-vendor SwarmKit to 4b872cfac8ffc0cc7fff434902cc05dbc7612da5

### PR DESCRIPTION
**Pull request by aluzzardi**
Related to docker/for-linux#2

/cc @mavenugo @andrewhsu @aaronlehmann 

Includes:
- docker/swarmkit#2203
- docker/swarmkit#2210
- docker/swarmkit#2212

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

Note that there is another swarmkit PR that is proposed for 17.06: https://github.com/docker/swarmkit/pull/2211

**Comment by cyli** [comment]
Actually apologies, I'd like to also propose https://github.com/docker/swarmkit/pull/2213 although it's less show-stopping.

**Comment by andrewhsu** [comment]
This PR brings in git commit https://github.com/docker/swarmkit/commit/f7a002c5f1d497158c211285813c3b10d6d0f5c5 into the engine's vendor dir to address issue https://github.com/docker/swarmkit/pull/2203

I've confirmed the vendor.conf change in this PR is only pulling in the one desired commit without the tests (because vndr would have stripped the test out of the vendor dir):
https://github.com/docker/swarmkit/compare/1a3e510517be82d18ac04380b5f71eddf06c2fc0...f7a002c5f1d497158c211285813c3b10d6d0f5c5

**Comment by andrewhsu** [comment]
i rebased

**Comment by andrewhsu** [comment]
LGTM

integration tests and unit tests are green

**Pull request merged**
