### PR TITLE
[17.09] cli updated vendoring

### PR DESCRIPTION
**Pull request by vieux**
backport:
* docker/cli/pull/424 updated vendoring
* moby/moby#34761 Some cleanup of mount create API test
* docker/cli/pull/516 vndr docker/docker to ea220e7 to bring in fix for arm
* docker/cli/pull/528 vndr github.com/docker/docker to 84144a8 to fix stuff
* docker/cli/pull/510 Use a local copy of ParseLogDetails
* moby/moby/pull/34829 LCOW: Spot fix for multi-os image pulling
```
$ git cherry-pick -s -x -Xsubtree=components/cli a0113c3a448cb1ed875f2116eb8436ee8bd97bfc
$ git cherry-pick -s -x -Xsubtree=components/cli 724f03bb23bae4339edf6af5017ae695dd977f2f
$ git cherry-pick -s -x -Xsubtree=components/engine 58b96aced87b33c4175fa5d3422289f763ab599d
$ git cherry-pick -s -x -Xsubtree=components/cli ef027b6d7292b0ed249e70294f5f23c51a68e794
$ git cherry-pick -s -x -Xsubtree=components/cli 50696bbf72b4177bb324fc411be3121b6e935b9f
$ git cherry-pick -s -x -Xsubtree=components/cli 536da4a07a79de929e9e6857220a9a941f6a46ef
$ git cherry-pick -s -x -Xsubtree=components/cli 850b46e67cd96f7bd4fe49937305fdd7748049df
$ git cherry-pick -s -x -Xsubtree=components/cli a747389bf4180881f658b45fac2296306072756c
$ git cherry-pick -s -x -Xsubtree=components/engine b291f5a31728f7ff6386bb37f15e7c0885d3b2a7
```

cherry-pick was clean, no conflict

### CODE REVIEW

**Comment by andrewhsu** [comment]
Analysis of build results show that `DockerSuite.TestRunAttachDetachFromInvalidFlag` test is now passing because of this PR:
```
$ ./check_failures.sh https://jenkins.dockerproject.org/job/docker-ce-pr/168/consoleText
FOR: https://jenkins.dockerproject.org/job/docker-ce-pr/168/consoleText

Passed (thought would fail):
DockerSuite.TestRunAttachDetachFromInvalidFlag
DockerSwarmSuite.TestServiceLogs
DockerSwarmSuite.TestSwarmNetworkPluginV2
DockerSwarmSuite.TestSwarmServicePsMultipleServiceIDs

Failed (should fail)
DockerSuite.TestRmiContainerImageNotFound
DockerSuite.TestRmiImageIDForceWithRunningContainersAndMultipleTags
DockerSuite.TestRunWithNanoCPUs
DockerSuite.TestUpdateWithNanoCPUs

Failed (thought would pass):
DockerSuite.TestContainersAPICreateMountsCreate
DockerSuite.TestRunEnvironment
```

**Comment by vieux** [comment]
but it's also adding 2 new failures :/

**Comment by dnephin** [comment]
TestRunEnvironment is a flaky test, see https://github.com/moby/moby/pull/34757 , so we can ignore that failure.

I will look into TestContainersAPICreateMountsCreate now. 

Do you want to re-open this issue? We need it to fix a real failure (TestRunAttachDetachFromInvalidFlag)

**Comment by dnephin** [comment]
TestContainersAPICreateMountsCreate should be fixed by https://github.com/moby/moby/pull/34761

It was caused by https://github.com/moby/moby/pull/34487

The test is calling `docker volume inspect ""` (yes with an empty volume name). Previously that would be an error, but because of https://github.com/moby/moby/pull/34487 the client performs the API call to `/v1.32/volumes` instead of `/v1.30/volumes/`, which doesn't produce an error and since it returns a valid json object it decodes it into the empty Volume that we see printed.

I guess we can also fix this in the client to return an error when the ID is empty.

**Comment by dnephin** [comment]
https://github.com/moby/moby/pull/34770 also fixed `TestContainersAPICreateMountsCreate` once it gets vendored into docker/cli

**Comment by vieux** [comment]
added moby/moby#34761

**Comment by vieux** [comment]
alight, that's very encouraging for 17.10. unfortunatly, merge such PR after the initial code freeze seems very risky to me, so I don't think we should merge it now.

@andrewhsu @dnephin @tiborvass

**Comment by dnephin** [comment]
Don't we need this to fix the panic in docker/cli (https://github.com/docker/cli/issues/380) ?

This is mostly just vendoring and test changes, so I would be fine to merge it. The risk is pretty low.

**Comment by vieux** [comment]
@dnephin correct, I fixed the last commit. I think we are ready to merge this one.

**Comment by vieux** [comment]
@andrewhsu I added https://github.com/docker/cli/pull/516

**Comment by andrewhsu** [comment]
@dnephin seeing just [1 failure](https://jenkins.dockerproject.org/job/docker-ce-pr/183/execution/node/253/log/?consoleFull) from the `ce-tests`:
```
[DockerSuite] FAIL: docker_api_containers_test.go:1894: DockerSuite.TestContainersAPICreateMountsCreate
[DockerSuite] 
[DockerSuite] case 0 - config: {volume  /foo false  <nil> <nil> <nil>}
[DockerSuite] case 1 - config: {volume  /foo/ false  <nil> <nil> <nil>}
[DockerSuite] case 2 - config: {volume test1 /foo false  <nil> <nil> <nil>}
[DockerSuite] case 3 - config: {volume test2 /foo true  <nil> <nil> <nil>}
[DockerSuite] case 4 - config: {volume test3 /foo false  <nil> 0xc420233f80 <nil>}
[DockerSuite] case 5 - config: {bind /tmp/test-mounts-api-1625168725 /foo false  <nil> <nil> <nil>}
[DockerSuite] docker_api_containers_test.go:2018:
[DockerSuite]     c.Assert(err, checker.NotNil, check.Commentf(out))
[DockerSuite] ... value = nil
[DockerSuite] ... [
[DockerSuite]     {
[DockerSuite]         "Driver": "",
[DockerSuite]         "Labels": null,
[DockerSuite]         "Mountpoint": "",
[DockerSuite]         "Name": "",
[DockerSuite]         "Options": null,
[DockerSuite]         "Scope": ""
[DockerSuite]     }
[DockerSuite] ]
```

**Comment by andrewhsu** [comment]
I think the point to vndr for github.com/docker/docker did not include enough fixes. I've created another PR to have docker/cli vendor to the latest on moby/moby: https://github.com/docker/cli/pull/528

**Comment by vieux** [comment]
I added https://github.com/docker/cli/pull/528

**Comment by dnephin** [comment]
Looks like CI failed, but changes look good

**Comment by andrewhsu** [comment]
I think this is a reproducible error:
```
$ cd components/cli
$ make -f docker.Makefile binary
...
Building statically linked build/docker-linux-amd64
# github.com/docker/cli/cli/command/service
cli/command/service/logs.go:260: undefined: "github.com/docker/cli/vendor/github.com/docker/docker/client".ParseLogDetails
make: *** [Makefile:31: binary] Error 2
make: *** [binary] Error 2
```

**Comment by dnephin** [comment]
Yes, you'll need https://github.com/docker/cli/pull/510

**Comment by vieux** [comment]
@dnephin I added it, thanks

**Comment by andrewhsu** [comment]
The `ce-tests` looking green, just one [failure on the windows job](https://jenkins.dockerproject.org/job/docker-ce-pr-WoW-RS1/386/console):
```
FAIL: docker_cli_pull_test.go:273: DockerSuite.TestPullLinuxImageFailsOnWindows

docker_cli_pull_test.go:276:
    c.Assert(err.Error(), checker.Contains, "cannot be used on this platform")
... obtained string = "" +
...     "\n" +
...     "Command:  d:\\CI\\CI-c6e21043d8\\binary\\docker.exe pull ubuntu\n" +
...     "ExitCode: 1\n" +
...     "Error:    exit status 1\n" +
...     "Stdout:   Using default tag: latest\n" +
...     "latest: Pulling from library/ubuntu\n" +
...     "\n" +
...     "Stderr:   no matching manifest for windows/amd64 in the manifest list entries\n" +
...     "\n" +
...     "\n" +
...     "Failures:\n" +
...     "ExitCode was 1 expected 0\n" +
...     "Expected no error"
... substring string = "cannot be used on this platform"
```

cc @johnstep

**Comment by johnstep** [comment]
This is fixed by https://github.com/moby/moby/pull/34829.

**Pull request merged**
