### PR TITLE
[18.03] disallow attaching ingress network

### PR DESCRIPTION
**Pull request by thaJeztah**
This PR brings in https://github.com/docker/swarmkit/pull/2523; https://github.com/docker/swarmkit/compare/49a9d7f6ba3c1925262641e694c18eb43575f74b...11d7b06f48bc1d73fc6d8776c3552a4b11c94301

CLI vendoring is also updated, but did not bring in changes

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @andrewhsu @fcrisciani @anshulpundir PTAL

**Comment by thaJeztah** [comment]
1 failure on Windows; doesn't look related; https://jenkins.dockerproject.org/job/docker-ce-pr-WoW-RS1/803/console

```
16:15:55 ----------------------------------------------------------------------
16:15:55 FAIL: docker_cli_run_test.go:4374: DockerSuite.TestSlowStdinClosing
16:15:55 
16:15:55 docker_cli_run_test.go:4390:
16:15:55     c.Fatal("running container timed out") // cleanup in teardown
16:15:55 ... Error: running container timed out
16:15:55 
```

**Comment by thaJeztah** [comment]
Rebased, to get rid of the commits from https://github.com/docker/docker-ce/pull/451

**Comment by andrewhsu** [comment]
Seeing a [failure](https://jenkins.dockerproject.org/job/docker-ce-pr-s390x/441/execution/node/483/log/) only in s390x on the `DockerSwarmSuite.TearDownTest` from the latest commit, but had s390x [success](https://jenkins.dockerproject.org/job/docker-ce-pr-s390x/439/execution/node/429/log/) before the rebase.

**Comment by thaJeztah** [comment]
It's failing in the `DockerSwarmSuite.TestSwarmLockUnlockCluster` test; I've seen that fail in other locations (I think mostly on s390); we should probably look if there's an actual issue somewhere, but I don't think it's related to this PR.

**Pull request merged**
