### PR TITLE
Clarify user ID for docker attach

### PR DESCRIPTION
**Pull request by mstanleyjones**
Clarification was requested from @aaronlehmann while working on https://github.com/docker/docker.github.io/pull/3494

### CODE REVIEW

**Comment by mstanleyjones** [comment]
cc/ @mlaventure @thaJeztah

**Comment by thaJeztah** [comment]
@mstanleyjones should this be in the moby/moby or docker/cli repository first?

**Comment by thaJeztah** [comment]
Oh, and against the 17.06 release branch if it needs to go in there https://github.com/docker/docker-ce/tree/17.06

**Comment by aaronlehmann** [comment]
Thanks. I'm still not completely sure about talking about different users on the host - end users interact with Docker through a client, and the Docker daemon itself doesn't know or care which user account the client is running as, or even which host it's running on. But this is definitely better than the previous wording. LGTM.

**Comment by seemethere** [comment]
@andrewhsu should this get merged into the upstream repo instead?

**Comment by mlaventure** [comment]
@thaJeztah is correct, we don't accept changes to components on the master branch, only in the release branches.

If this is to be cherry-picked into the 17.06 release branch, it should first get merged in the upstream component.

**Comment by mstanleyjones** [comment]
@aaronlehmann the thing I was trying to convey is that other users on the host can attach to a running container, even if they were not the ones that started that container.

Thanks all, I'll re-open this in the right repo. cc/ @tibor as FYI because we were not sure about process.

**Comment by tibor** [comment]
@mstanleyjones I don’t think you meant me, did you?

**Comment by mstanleyjones** [comment]
No sorry, @tiborvass :/ It's not my day.

**Pull request closed without merging**
