### PR TITLE
Vendoring libnetwork 4f5310be349d9299f6cab6d5822312f00cfa965c

### PR DESCRIPTION
**Pull request by mavenugo**
This is a cherry-pick of https://github.com/moby/moby/pull/33634
that brings in https://github.com/docker/libnetwork/pull/1796.

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
The RS1 test failure is flaky and tracked under https://github.com/moby/moby/issues/32219

**Comment by andrewhsu** [comment]
Looks like this PR also brings in https://github.com/docker/libnetwork/pull/1803

**Comment by mavenugo** [comment]
@andrewhsu yes. but it is part of https://github.com/docker/libnetwork/pull/1796 which we missed and hence a new PR was opened. 

Essentially its all part of https://github.com/docker/libnetwork/pull/1796.

**Comment by andrewhsu** [comment]
LGTM

**Pull request merged**
