### PR TITLE
[17.09] add 17.09 changelog

### PR DESCRIPTION
**Pull request by vieux**
This is WIP and automatically generated.

Before I continue the manual triage tomorrow, I'd like to make sure we have all the commits needed.

### CODE REVIEW

**Comment by vieux** [comment]
@tonistiigi anything missing on the builder ?
@fcrisciani anything mission for the networking ?

**Comment by tonistiigi** [comment]
@vieux maybe moby/moby#33704

**Comment by fcrisciani** [comment]
@vieux I would also mention: https://github.com/docker/libnetwork/pull/1877

**Comment by vieux** [comment]
@fcrisciani @tonistiigi done

**Comment by fcrisciani** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by shouze** [comment]
@vieux would really love to have a fix for https://github.com/moby/moby/issues/32816 merged in docker/cli at time for 17.09 but stucked ATM with logrus & [Ss]irupsen mess blocking me to upgrade vendors after the merge of https://github.com/moby/moby/pull/34590. https://github.com/docker/notary/pull/1211 seems to be the last bastion to fix https://github.com/docker/cli/issues/465 and rollout the plan.

**Pull request merged**
