### PR TITLE
[17.06.1] Re-vendor swarmkit

### PR DESCRIPTION
**Pull request by cyli**
This includes changes from 
- [x] https://github.com/docker/swarmkit/pull/2224

To fix a long timeout/delay for a root rotation edge case.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
This should not be merged yet, correct?

**Comment by cyli** [comment]
@aaronlehmann  That's true - this is for 17.06.1

**Comment by seemethere** [comment]
Re-kicked the `ce-tests` on this, seems like it's getting the same `400 Bad Request` error that's messing with a lot of other jobs.

**Comment by andrewhsu** [comment]
Closing this in favour of PR #84 Fix swarmkit issues for 17.06.0-rc5

**Pull request closed without merging**
