### PR TITLE
[18.03] move trust out of experimental

### PR DESCRIPTION
**Pull request by vdemeester**
Cherry-picks — were not clean, conflicts on unit tests.

```bash
git cherry-pick -Ss -x -Xsubtree=components/cli c5554f811b385f84e57d57bf89d97d4ec1efe1e3 # conflicts
git cherry-pick -Ss -x -Xsubtree=components/cli 8c3d0b93d631f948376a81c7baecc6dad88ce248 # conflicts
git cherry-pick -Ss -x -Xsubtree=components/cli ac35e851e858b61b0b93167d94708b6e90e4b954
git cherry-pick -Ss -x -Xsubtree=components/cli 09ec6d4ad9f7040918f410e7382095dd70570261
git cherry-pick -Ss -x -Xsubtree=components/cli 2a6808db87229fb4269251f6bd69e9079cc827b4
```

Backport fix(es) from:

* docker/cli#934 Refactor trust view command into a --pretty flag on trust inspect
* docker/cli#935 Move Docker Trust out of experimental
* docker/cli#944 Bash: update trust completions

cc @andrewhsu @n4ss @vieux @thaJeztah

### CODE REVIEW

**Comment by thaJeztah** [comment]
PowerPC is failing on

```
09:11:54 PASS: docker_cli_events_unix_test.go:51: DockerSuite.TestEventsOOMDisableFalse	1.519s
09:16:57 --- FAIL: Test (1635.35s)
09:16:57 panic: DockerSuite.TestEventsOOMDisableTrue test timed out after 5m0s [recovered]
09:16:57 	panic: DockerSuite.TestEventsOOMDisableTrue test timed out after 5m0s
```

We should cherry-pick https://github.com/moby/moby/pull/36539 here (let me open a PR)

**Comment by n4ss** [comment]
LGTM! ⚽️

**Comment by vdemeester** [comment]
:soccer: :tada: :stuck_out_tongue_closed_eyes:

**Comment by andrewhsu** [comment]
#460 has been merged to address the ppc64le oom failure

**Pull request merged**
