### PR TITLE
[17.07] Fix wrong changelog entries

### PR DESCRIPTION
**Pull request by albers**
These issues also exist in the release notes. They should be fixed there as well.

### CODE REVIEW

**Comment by albers** [comment]
CI failures are unrelated. This is a docs-only PR.

**Comment by vieux** [comment]
@albers could you also please add `(experimental)` in front of `Implement long running interactive session and sending build context incrementally` while your at it ?

**Comment by albers** [comment]
@vieux done.

**Comment by vieux** [comment]
LGTM

**Pull request merged**
