### PR TITLE
Vendor swarmkit 98e5a93

### PR DESCRIPTION
**Pull request by aaronlehmann**
This vendors the 17.06 branch of swarmkit. It brings in one bug fix:

- allocator: Avoid assigning duplicate IPs during initialization (https://github.com/docker/swarmkit/pull/2237)

### CODE REVIEW

**Comment by mavenugo** [comment]
The RS1 test failure is flaky and tracked under https://github.com/moby/moby/issues/32219

**Comment by cyli** [comment]
I've cherry-picked https://github.com/docker/swarmkit/pull/2234, waiting on https://github.com/docker/swarmkit/pull/2238 currently.

**Comment by cyli** [comment]
docker/swarmkit#2238 cherry-picked and pushed to `bump_v17.0.6`

**Comment by aaronlehmann** [comment]
Updated to include docker/swarmkit#2234 and docker/swarmkit#2238.

**Comment by aaronlehmann** [comment]
Closing in favor of #69, which is identical.

**Pull request closed without merging**
