### PR TITLE
revendor github.com/docker/swarmkit to ef3c57a

### PR DESCRIPTION
**Pull request by andrewhsu**
To get the changes:
* docker/swarmkit#2234 [ca] Validate the Root CA certificate before updating the security config
* docker/swarmkit#2237 allocator: Avoid assigning duplicate IPs during initialization
* docker/swarmkit#2238 [ca/node] Maybe update the root CA when renewing the TLS cert

The changes between the two commit hashes on docker/swarmkit repo:
https://github.com/docker/swarmkit/compare/758b59114f7eef55faca7007af773d4097540ed2...6083c7689ed00a6f2d67941443603df69c2ff6ba

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@andrewhsu @aaronlehmann shall we also get https://github.com/docker/swarmkit/pull/2244 in ?
This will fix a P0 and it will be great to have all known P0s in RC3. Which can help avoid RC4 if there are no more P0s found.

**Comment by aaronlehmann** [comment]
This looks like a duplicate of #67.

**Comment by aaronlehmann** [comment]
Although, to be fair, this one got the full set of changes before #67 was updated to have them all.

**Comment by andrewhsu** [comment]
LGTM

integration and unit tests are green

**Pull request merged**
