### PR TITLE
[17.06] Completion cherry picks

### PR DESCRIPTION
**Pull request by thaJeztah**
Bash completion fixes:

* https://github.com/docker/cli/pull/254 https://github.com/docker/cli/commit/36b572dfdf6bc7b2519f494afe93130e3a8718b5
* https://github.com/docker/cli/pull/279 https://github.com/docker/cli/commit/1f8720717d58597cb4474e70fa6d534db132229b
* https://github.com/docker/cli/pull/280 https://github.com/docker/cli/commit/1d21a3dd7c4ffff80c093c005b910a131e7fc05a
* https://github.com/docker/cli/pull/281 https://github.com/docker/cli/commit/2caf425f02363a5894b5790dcde47a11808d23e1
* https://github.com/docker/cli/pull/283 https://github.com/docker/cli/commit/c40952b3058db3c6e44bca8c518d888b83878ce5 https://github.com/docker/cli/commit/211bd55ae736705a48908833a5e10491f613e255 https://github.com/docker/cli/commit/d585e554d5e3a16f424cb3d92d0f7be342b8c7ca
* https://github.com/docker/cli/pull/284 https://github.com/docker/cli/commit/fc0dafbbd11130ac24f8905f697b71e99f32d4e6

ZSH completion fixes:

* https://github.com/docker/cli/pull/368 https://github.com/docker/cli/commit/6b256484ae3cb4da78e6ddad75b8aaf552b9ae60
* https://github.com/docker/cli/pull/369 https://github.com/docker/cli/commit/d7ade64d29965a686ce7933865d273e84f1ccce1
* https://github.com/docker/cli/pull/371 https://github.com/docker/cli/commit/6c65ba6c0836ed14501cb40ad2d82cdde6fd168d

ping @andrewhsu @albers @jphuynh PTAL

### CODE REVIEW

**Comment by jphuynh** [comment]
LGTM for the zsh part. 👍

**Comment by albers** [comment]
LGTM for the bash completion part - all completions were successfully verified

**Comment by thaJeztah** [comment]
Thanks both!

ping @andrewhsu

**Comment by seemethere** [comment]
Re-kicked windows build, failure was unrelated to the PR

**Comment by thaJeztah** [comment]
ping @andrewhsu for merge

**Pull request merged**
